update logic so that workflows to be tested are specified

diff --git a/.github/workflows/run-workflow-tests.yml b/.github/workflows/run-workflow-tests.yml
--- a/.github/workflows/run-workflow-tests.yml
+++ b/.github/workflows/run-workflow-tests.yml
@@ -10,25 +10,26 @@ jobs:
   build-and-run:
     runs-on: ubuntu-latest
     env:
-      EXCLUDED_XIRCUITS: "path/to/excluded1.xircuits path/to/excluded2.xircuits"
-      # Uncomment the following line and specify paths to exclude additional .xircuits files
-      # EXCLUDED_XIRCUITS: "path/to/excluded1.xircuits path/to/excluded2.xircuits path/to/another_excluded.xircuits"
+      TEST_XIRCUITS: |
+        examples/example.xircuits
+        # path/to/your/workflow.xircuits
+        # Add more .xircuits files as needed, one per line
 
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
-
-    - name: Set COMPONENT_LIBRARY_PATH
-      run: |
-        REPO_NAME="${GITHUB_REPOSITORY##*/}"
-        COMPONENT_LIBRARY_PATH=$(echo "xai_components/xai_${REPO_NAME}" | sed 's/-/_/g')
-        echo "COMPONENT_LIBRARY_PATH=$COMPONENT_LIBRARY_PATH" >> $GITHUB_ENV
 
     - name: Install xircuits
       run: pip install xircuits
 
     - name: List xircuits
       run: xircuits list
+
+    - name: Set COMPONENT_LIBRARY_PATH
+      run: |
+        REPO_NAME="${GITHUB_REPOSITORY##*/}"
+        COMPONENT_LIBRARY_PATH=$(echo "xai_components/xai_${REPO_NAME}" | sed 's/-/_/g')
+        echo "COMPONENT_LIBRARY_PATH=$COMPONENT_LIBRARY_PATH" >> $GITHUB_ENV
 
     - name: Clone Pull Request
       run: |
@@ -37,38 +38,43 @@ jobs:
 
     - name: Test .xircuits Workflows
       run: |
-          export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
-          LOG_FILE="${GITHUB_WORKSPACE}/workflow_logs.txt"
-          echo "Looking for .xircuits files in ${{ env.COMPONENT_LIBRARY_PATH }}/*" | tee -a $LOG_FILE
-          FILES=$(find ${{ env.COMPONENT_LIBRARY_PATH }} -name "*.xircuits")
-          FAIL=0
-          if [ -z "$FILES" ]; then
-            echo "No .xircuits files found." | tee -a $LOG_FILE
-          else
-            for file in $FILES; do
-              if [[ $EXCLUDED_XIRCUITS != *"$file"* ]]; then
-                echo "Processing $file..." | tee -a $LOG_FILE
-                xircuits compile $file "${file%.*}.py" 2>&1 | tee -a $LOG_FILE
-                python "${file%.*}.py" 2>&1 | tee -a $LOG_FILE
-                RETVAL=$?
-                if [ $RETVAL -ne 0 ]; then
-                  echo "Error: Workflow $file failed with exit code $RETVAL" | tee -a $LOG_FILE
-                  FAIL=1
-                else
-                  echo "$file processed successfully" | tee -a $LOG_FILE
-                fi
+        export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
+        LOG_FILE="${GITHUB_WORKSPACE}/workflow_logs.txt"
+        IFS=$'\n' read -r -a TEST_FILES <<< "$TEST_XIRCUITS"
+        FAIL=0
+        if [ ${#TEST_FILES[@]} -eq 0 ]; then
+          echo "No .xircuits files specified for testing." | tee -a $LOG_FILE
+        else
+          for file in "${TEST_FILES[@]}"; do
+            FULL_PATH="${COMPONENT_LIBRARY_PATH}/${file}"
+            if [ -f "$FULL_PATH" ]; then
+              WORKFLOW_LOG_FILE="${FULL_PATH%.*}_workflow_log.txt"
+              echo "Processing $FULL_PATH..." | tee -a $LOG_FILE
+              xircuits compile $FULL_PATH "${FULL_PATH%.*}.py" 2>&1 | tee -a $LOG_FILE
+              python "${FULL_PATH%.*}.py" 2>&1 | tee -a $WORKFLOW_LOG_FILE
+              LAST_LINE=$(tail -n 1 "$WORKFLOW_LOG_FILE")
+              if [[ "$LAST_LINE" != "Finished Executing" ]]; then
+                echo "Error: Workflow $FULL_PATH did not finish as expected" | tee -a $LOG_FILE
+                FAIL=1
               else
-                echo "Skipping excluded file $file" | tee -a $LOG_FILE
+                echo "$FULL_PATH processed successfully" | tee -a $LOG_FILE
               fi
-            done
-            if [ $FAIL -ne 0 ]; then
-              echo "One or more workflows failed." | tee -a $LOG_FILE
-              exit 1
+              cat "$WORKFLOW_LOG_FILE" | tee -a $LOG_FILE
+            else
+              echo "Specified file $FULL_PATH does not exist" | tee -a $LOG_FILE
+              FAIL=1
             fi
-          fi
+          done
+        fi
+        if [ $FAIL -ne 0 ]; then
+          echo "One or more workflows failed or did not finish as expected." | tee -a $LOG_FILE
+          exit 1
+        else 
           echo "Workflow processing completed" | tee -a $LOG_FILE
+        fi
 
     - name: Upload log file
+      if: always()
       uses: actions/upload-artifact@v3
       with:
         name: workflow-logs
